# Generated by Django 5.2.3 on 2025-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
