# Generated by Django 5.2.1 on 2025-06-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default='14:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
