# Generated by Django 5.2.1 on 2025-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_hora_alter_restaurante_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
