# Generated by Django 5.2.1 on 2025-06-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_cantidad_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Imagen', models.ImageField(blank=True, upload_to='platos/')),
            ],
        ),
    ]
