# Generated by Django 5.2.1 on 2025-06-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_plato_precio_platoreserva_reserva_platos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='Imagen',
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
    ]
