# Generated by Django 5.2.1 on 2025-06-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_remove_plato_imagen_plato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pedido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
